[librm] Use explicit operand size when pushing a label address (bsc#1215311)
We currently use "push $1f" within inline assembly to push the address
of the real-mode code fragment, relying on the assembler to treat this
as "pushl" for 32-bit code or "pushq" for 64-bit code.

As of binutils commit 5cc0077 ("x86: further adjust extend-to-32bit-
address conditions"), first included in binutils-2.41, this implicit
operand size is no longer calculated as expected and 64-bit builds
will fail with

  Error: operand size mismatch for `push'

Fix by adding an explicit operand size to the "push" instruction.

Originally-fixed-by: Justin Cano <jstncno@gmail.com>
Signed-off-by: Michael Brown <mcb30@ipxe.org>
(cherry picked from commit 0aa2e4ec963597794dd8f8b36f77f4d0cf4e03c8)
References: bsc#1215311
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>