ipxe: Silence GCC 12 spurious warnings
Git-commit: 0000000000000000000000000000000000000000
References: bsc#1197018

With GCC 12, build fails like this:

[ 6245s]     inlined from 'memcpy_user' at
arch/x86/include/librm.h:155:2,
[ 6245s]     inlined from 'copy_from_user' at
include/ipxe/uaccess.h:338:2,
[ 6245s]     inlined from 'acpi_sx_zsdt' at core/acpi.c:217:3:
[ 6245s] arch/x86/include/bits/string.h:79:32: error: array subscript
'union <anonymous>[0]' is partly outside array bounds of 'union
<anonymous>[1]' [-Werror=array-bounds]
[ 6245s]    79 |                 dest_u->u32[0] = src_u->u32[0];
[ 6245s]       |                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
[ 6245s] core/acpi.c: In function 'acpi_sx_zsdt':
[ 6245s] core/acpi.c:191:11: note: object 'buf' of size 4
[ 6245s]   191 |         } buf;
[ 6245s]       |           ^~~

Which is a false positive reported by GCC compiler:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98503

Silence the watning.

Signed-off-by: Martin Liška <martin.liska@suse.com>
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>